export const REQUEST_GET_ENTRIES = "REQUEST_GET_ENTRIES";
export const RECEIVE_GET_ENTRIES = "RECEIVE_GET_ENTRIES";
export const REQUEST_ADD_ENTRY = "REQUEST_ADD_ENTRY";
export const RECEIVE_ADD_ENTRY = "RECEIVE_ADD_ENTRY";
export const REQUEST_DELETE_ENTRY = "REQUEST_DELETE_ENTRY";
export const RECEIVE_DELETE_ENTRY = "RECEIVE_DELETE_ENTRY";
export const REQUEST_EDIT_ENTRY = "REQUEST_EDIT_ENTRY";
export const RECEIVE_EDIT_ENTRY = "RECEIVE_EDIT_ENTRY";
export const REQUEST_SIGN_IN = "REQUEST_SIGN_IN";
export const RECEIVE_SIGN_IN = "RECEIVE_SIGN_IN";
export const REQUEST_REGISTER_USER = "REQUEST_REGISTER_USER";
export const RECEIVE_REGISTER_USER = "RECEIVE_REGISTER_USER";
export const SELECT_DATE = "SELECT_DATE";
export const REQUEST_CLEAR_ENTRIES = "REQUEST_CLEAR_ENTRIES";
export const REQUEST_SECURE_ENTRY = "REQUEST_SECURE_ENTRY";
export const RECEIVE_SECURE_ENTRY = "RECEIVE_SECURE_ENTRY";

export const SIGN_OUT = "SIGN_OUT";
